name: cps
favicon: null
layout_spectrum: 0.38848234550096095
typography_spectrum: 0.2679302617907524
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#66542e'
    - '#006591'
    - '#3b1719'
    - '#dee0cb'
    - '#948764'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
